name: Approval

on:
  pull_request:
    types: [opened, synchronize]

env:
  BRANCH: ${{ github.base_ref }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  token: ${{ vars.ACTION_GITHUB_TOKEN }}

jobs:
  check-approvers:
    name: Check approval
    runs-on: 
      group: APPROVAL
    steps:
      - name: Cleanup
        run: |
          rm -rf * .[^.]*
      - name: Update paddle
        run: |
          wget -q --no-proxy https://xly-devops.bj.bcebos.com/PaddleTest/PaddleNLP/PaddleNLP-develop.tar.gz --no-check-certificate
          tar zxf PaddleNLP-develop.tar.gz --strip-components=1 >/dev/null
          rm -rf PaddleNLP-develop.tar.gz >/dev/null
          git fetch origin pull/${PR_ID}/head
          git checkout -b origin_pr FETCH_HEAD
          git remote add upstream https://github.com/PaddlePaddle/PaddleNLP.git
          git fetch upstream
          git checkout -b test_pr upstream/${BRANCH}
          git merge --no-edit origin_pr
          git log --pretty=oneline -10

      - name: Check bypass
        id: check-bypass
        uses: ./.github/actions/check-bypass
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          workflow-name: approval
        
      - name: Display Required Approvers
        if: steps.check-bypass.outputs.can-skip != 'true'
        run: |
          cd scripts/ci_approval
          bash -x run_ci_approval.sh
